name: app_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_gen_runner: ^5.11.0
  build_runner: ^2.6.0
  flutter_svg: ^2.2.0
  google_fonts: ^6.3.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_gen:
  assets:
    enabled: true
    outputs:
      class_name: AppIcons
      package_parameter_enabled: true
  output: lib/src/gen/
  integrations:
    flutter_svg: true
